import json
import shutil
import subprocess
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from typing import TypedDict

from .config import load_config
from .download import download_pdf
from .store import Paper, StoreError, list_papers

DRIVE_URL = "https://drive.google.com/file/d/{}/view"
MAP_FILE = "map.md"
DRIVE_FILE = "drive.json"
TRACKED = ["bib", "reading", MAP_FILE, DRIVE_FILE]


class SyncReport(TypedDict):
    pulled: list[str]
    fetched: list[str]
    uploaded: bool
    linked: int
    pushed: bool


def _run(cmd: list[str], cwd: Path) -> subprocess.CompletedProcess[str]:
    if shutil.which(cmd[0]) is None:
        raise StoreError(f"`{cmd[0]}` is not installed.")
    return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, check=False)


def _check(cmd: list[str], cwd: Path) -> str:
    result = _run(cmd, cwd)
    if result.returncode != 0:
        detail = result.stderr.strip() or result.stdout.strip()
        raise StoreError(f"`{' '.join(cmd[:2])}` failed: {detail}")
    return result.stdout


def _has_remote(library: Path) -> bool:
    if not (library / ".git").exists():
        return False
    return bool(_check(["git", "remote"], library).strip())


def _keys(library: Path) -> set[str]:
    return {path.stem for path in (library / "bib").glob("*.bib")}


def _commit(library: Path, message: str) -> bool:
    present = [name for name in TRACKED if (library / name).exists()]
    _check(["git", "add", "-A", "--", *present], library)
    if _run(["git", "diff", "--cached", "--quiet"], library).returncode == 0:
        return False
    _check(["git", "commit", "-m", message], library)
    return True


def pull(library: Path) -> list[str]:
    before = _keys(library)
    _commit(library, "sync: local changes")
    _check(["git", "pull", "--rebase", "--autostash"], library)
    return sorted(_keys(library) - before)


def fetch_missing_pdfs(keys: list[str]) -> list[str]:
    wanted = set(keys)
    missing = [p for p in list_papers() if p["key"] in wanted and not p["has_pdf"]]
    if not missing:
        return []
    with ThreadPoolExecutor(max_workers=4) as pool:
        outcomes = list(pool.map(download_pdf, missing))
    return sorted(
        paper["key"] for paper, outcome in zip(missing, outcomes) if outcome["pdf"]
    )


def upload(library: Path, remote: str) -> None:
    _check(
        ["rclone", "copy", str(library / "pdf"), remote, "--include", "*.pdf"], library
    )


def drive_ids(library: Path, remote: str) -> dict[str, str]:
    listing = json.loads(
        _check(["rclone", "lsjson", remote, "--files-only"], library) or "[]"
    )
    return {
        Path(item["Name"]).stem: item["ID"]
        for item in listing
        if item["Name"].endswith(".pdf") and item.get("ID")
    }


def load_drive_ids(library: Path) -> dict[str, str]:
    path = library / DRIVE_FILE
    if not path.is_file():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def drive_link(paper: Paper) -> str:
    file_id = load_drive_ids(Path(paper["folder"])).get(paper["key"], "")
    return DRIVE_URL.format(file_id) if file_id else ""


def _cell(text: str) -> str:
    cleaned = text.replace("|", "/").replace("{", "").replace("}", "")
    return " ".join(cleaned.split())


def _short_authors(authors: str) -> str:
    names = [name.strip() for name in authors.split(" and ") if name.strip()]
    if not names:
        return ""
    first = names[0].split(",")[0].strip()
    return f"{first} et al." if len(names) > 1 else first


def render_map(papers: list[Paper], ids: dict[str, str]) -> str:
    lines = [
        "# Library map",
        "",
        f"{len(papers)} papers. Generated by `cocotero sync`; do not edit.",
        "",
        "| key | year | title | authors | categories | doi | pdf |",
        "|---|---|---|---|---|---|---|",
    ]
    for paper in papers:
        file_id = ids.get(paper["key"], "")
        pdf = DRIVE_URL.format(file_id) if file_id else "none"
        cells = [
            paper["key"],
            paper["year"],
            paper["title"],
            _short_authors(paper["authors"]),
            paper["categories"],
            paper["doi"],
            pdf,
        ]
        lines.append("| " + " | ".join(_cell(cell) for cell in cells) + " |")
    return "\n".join(lines) + "\n"


def write_map(library: Path, ids: dict[str, str]) -> None:
    (library / DRIVE_FILE).write_text(
        json.dumps(ids, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    (library / MAP_FILE).write_text(render_map(list_papers(), ids), encoding="utf-8")


def sync_library() -> SyncReport:
    cfg = load_config()
    library = Path(cfg["library"])
    remote = cfg["drive_remote"]
    git = _has_remote(library)
    pulled = pull(library) if git else []
    fetched = fetch_missing_pdfs(pulled)
    ids = load_drive_ids(library)
    if remote:
        upload(library, remote)
        ids = drive_ids(library, remote)
    write_map(library, ids)
    pushed = False
    if git:
        _commit(library, f"sync: {len(ids)} PDFs on Drive")
        _check(["git", "push"], library)
        pushed = True
    return {
        "pulled": pulled,
        "fetched": fetched,
        "uploaded": bool(remote),
        "linked": len(ids),
        "pushed": pushed,
    }
